// front-vue/src/pages/Wishlist.vue
<script setup lang="ts">
import axios from "axios";
import { ref } from "vue";

import Header from "../components/Header.vue";
import Navigation from "../components/Navigation.vue";
import ProductCard from "../components/ProductCard.vue";

import { getWishlist } from "../utils/customLocalStorage";

const products = ref([]);

const fetchWishlist = () => {
  const wishlist = getWishlist();
  products.value = wishlist;
};

fetchWishlist();
</script>

<template>
  <Header />
  <Navigation />

  <div
    class="w-full px-4 sm:px-20 mt-8 grid gap-10 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
  >
    <ProductCard
      v-for="product of products"
      :key="product.code"
      :product="product"
      @updateWishlist="fetchWishlist"
    />
  </div>
</template>

// front/src/pages/Wishlist/index.tsx
import { useLayoutEffect, useState } from "react";

import { Header } from "../../components/Header";
import { Navigation } from "../../components/Navigation";
import { ProductCard } from "../../components/ProductCard";

import { getWishlist } from "../../utils/customLocalStorage";
import type { IProduct } from "../../utils/interfaces/Product";

import { PageDefault } from "../../styles";
import { Content } from "./styles";

export function Wishlist() {
  const [wishlist, setWishlist] = useState<IProduct[]>([]);

  const fetchWishlist = async () => {
    const wishlist = getWishlist();
    setWishlist(wishlist);
  };

  useLayoutEffect(() => {
    fetchWishlist();
  }, []);

  return (
    <PageDefault>
      <Header />
      <Navigation />

      <Content>
        {wishlist.map((product) => (
          <ProductCard
            key={product.code}
            product={product}
            setWishlist={setWishlist}
          />
        ))}
      </Content>
    </PageDefault>
  );
}
